# Site settings
title: Blog của brucebinh
email: brucebinh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog của brucebinh
baseurl: "/" # the subpath of your site, e.g. /blog/
url: http://dongxoai.net # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: brucebinh

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter: brucebinh
facebook: brucebinh
github: brucebinh
instagram: brucebinh
linkedin: brucebinh

ga:
  id: UA-105605074-1
  url: dongxoai.net
owner:
  name:           Bui Danh Binh
  avatar:         http://graph.facebook.com/100002503874264/picture?width=100&height=100

# avatar and Favicon
avatar: http://graph.facebook.com/100002503874264/picture?width=100&height=100

# Build settings
permalink: /:year/:month/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-figure

future: true